[platformio]
default_envs = m5stick-c-plus2

[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_flags =
  -D ARDUINOJSON_ENABLE_ARDUINO_STRING=1
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.2
  bblanchon/ArduinoJson@^7.0.4
