name: Firmware

on:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/build-firmware.yml"
  pull_request:
    paths:
      - "firmware/**"
      - ".github/workflows/build-firmware.yml"

jobs:
  platformio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install platformio
      - run: pio run -d firmware
